apiVersion: v1
entries:
  opentelemetry-collector:
  - apiVersion: v2
    appVersion: 0.78.0
    created: "2023-05-31T10:52:45.559742884-04:00"
    description: OpenTelemetry Collector Helm chart for Kubernetes
    digest: eb6a5b2714831a9679f25e689ddb73a7a4c7fc5e904575587e542205b9a57062
    home: https://opentelemetry.io/
    icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
    maintainers:
    - name: dmitryax
    - name: TylerHelmuth
    name: opentelemetry-collector
    sources:
    - https://github.com/open-telemetry/opentelemetry-collector
    - https://github.com/open-telemetry/opentelemetry-collector-contrib
    type: application
    urls:
    - opentelemetry-collector-0.59.1.tgz
    version: 0.59.1
  opentelemetry-demo:
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2023-05-31T10:52:45.564231113-04:00"
    dependencies:
    - condition: opentelemetry-collector.enabled
      name: opentelemetry-collector
      repository: https://open-telemetry.github.io/opentelemetry-helm-charts
      version: 0.55.1
    - condition: jaeger.enabled
      name: jaeger
      repository: https://jaegertracing.github.io/helm-charts
      version: 0.69.1
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 20.2.0
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.52.8
    description: opentelemetry demo helm chart
    digest: d389dc1e365348bdf29a243f1134cc26c72704e5cabadd9c32e038242fdc0257
    home: https://opentelemetry.io/
    icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
    maintainers:
    - name: dmitryax
    - name: puckpuck
    - name: tylerhelmuth
    name: opentelemetry-demo
    sources:
    - https://github.com/open-telemetry/opentelemetry-demo
    type: application
    urls:
    - opentelemetry-demo-0.22.3.tgz
    version: 0.22.3
  opentelemetry-operator:
  - apiVersion: v2
    appVersion: 0.77.0
    created: "2023-05-31T10:52:45.565716476-04:00"
    description: OpenTelemetry Operator Helm chart for Kubernetes
    digest: 632ed59d13ddf91283864a07a8a477cf4befabe3133d4a57e59628c9e3d7b055
    home: https://opentelemetry.io/
    icon: https://raw.githubusercontent.com/cncf/artwork/a718fa97fffec1b9fd14147682e9e3ac0c8817cb/projects/opentelemetry/icon/color/opentelemetry-icon-color.png
    maintainers:
    - name: Allex1
    - name: dmitryax
    - name: TylerHelmuth
    name: opentelemetry-operator
    sources:
    - https://github.com/open-telemetry/opentelemetry-operator
    type: application
    urls:
    - opentelemetry-operator-0.30.1.tgz
    version: 0.30.1
generated: "2023-05-31T10:52:45.55828536-04:00"
